CREATE TABLE IF NOT EXISTS ad_run_token_usage (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    run_id BIGINT NOT NULL COMMENT '运行记录ID，关联 ad_run.id',
    requirement_pk BIGINT NOT NULL COMMENT '需求主键ID，关联 ad_requirement.id',
    job_id BIGINT NULL COMMENT '任务ID，关联 ad_job.id',
    client_session_id BIGINT NULL COMMENT '执行客户端会话ID，关联 ad_client_session.id',
    agent_id VARCHAR(64) NULL COMMENT '执行使用的 Agent Provider ID',
    stage VARCHAR(32) NULL COMMENT '流程阶段：PRD、TECH_DESIGN、IMPLEMENTATION、CODE_REVIEW、RETROSPECTIVE',
    implementation_step VARCHAR(64) NULL COMMENT '实施阶段细分步骤',
    model VARCHAR(128) NULL COMMENT '模型名称，未知时为空',
    source_event_type VARCHAR(64) NOT NULL COMMENT '来源事件类型，如 turn.completed',
    usage_fingerprint CHAR(64) NOT NULL COMMENT '用量明细幂等指纹',
    input_tokens BIGINT NOT NULL DEFAULT 0 COMMENT '输入 token 数',
    cached_input_tokens BIGINT NOT NULL DEFAULT 0 COMMENT '缓存输入 token 数',
    output_tokens BIGINT NOT NULL DEFAULT 0 COMMENT '输出 token 数',
    reasoning_output_tokens BIGINT NOT NULL DEFAULT 0 COMMENT '推理输出 token 数',
    total_tokens BIGINT NOT NULL DEFAULT 0 COMMENT '总 token 数',
    raw_usage_json JSON NULL COMMENT '原始 usage JSON',
    occurred_at DATETIME NOT NULL COMMENT '用量发生时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0 未删除，1 已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_run_fingerprint (run_id, usage_fingerprint),
    KEY idx_requirement_time (requirement_pk, occurred_at),
    KEY idx_agent_time (agent_id, occurred_at),
    KEY idx_client_time (client_session_id, occurred_at),
    KEY idx_run_time (run_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI交付运行 token 用量明细表';
