-- Store active technical-design annotations in Center DB.

CREATE TABLE IF NOT EXISTS ad_tech_design_annotation (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    requirement_pk BIGINT NOT NULL COMMENT '需求主键ID，关联 ad_requirement.id',
    annotation_uid VARCHAR(64) NOT NULL COMMENT '对外稳定批注ID',
    artifact_path VARCHAR(512) NOT NULL COMMENT '批注所属技术方案路径',
    version_id VARCHAR(128) NOT NULL COMMENT '技术方案版本ID',
    version_no INT NULL COMMENT '技术方案版本号',
    version_source VARCHAR(64) NULL COMMENT '版本来源：CURRENT_DRAFT、PUBLISHED、DRAFT_SNAPSHOT',
    content_hash VARCHAR(128) NULL COMMENT '版本正文Hash',
    selected_text VARCHAR(2000) NOT NULL COMMENT '选中文案',
    comment_text VARCHAR(4000) NOT NULL COMMENT '批注意见',
    plain_start INT NOT NULL DEFAULT 0 COMMENT '纯文本起始位置',
    plain_end INT NOT NULL DEFAULT 0 COMMENT '纯文本结束位置',
    prefix_text VARCHAR(500) NULL COMMENT '前文锚点',
    suffix_text VARCHAR(500) NULL COMMENT '后文锚点',
    heading_path_json VARCHAR(2000) NULL COMMENT '标题路径JSON',
    occurrence INT NOT NULL DEFAULT 1 COMMENT '选中文案出现序号',
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN' COMMENT '状态：OPEN、RESOLVED、CARRIED_FORWARD、STALE',
    include_in_next_generation TINYINT NOT NULL DEFAULT 1 COMMENT '是否纳入下一次技术方案生成',
    consumed_at DATETIME NULL COMMENT '成功生成消费时间',
    consumed_run_id VARCHAR(128) NULL COMMENT '消费该批注的运行ID',
    created_by BIGINT NOT NULL COMMENT '创建人用户ID',
    updated_by BIGINT NULL COMMENT '最近更新人用户ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0 未删除，1 已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_requirement_annotation (requirement_pk, annotation_uid),
    KEY idx_requirement_version (requirement_pk, version_id),
    KEY idx_requirement_consumed (requirement_pk, consumed_at),
    KEY idx_requirement_status (requirement_pk, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI交付技术方案批注表';
